#[path = "create-calendar.rs"]
pub mod create_calendar;
#[path = "create-item.rs"]
pub mod create_item;
#[path = "delete-calendar.rs"]
pub mod delete_calendar;
#[path = "delete-item.rs"]
pub mod delete_item;
#[path = "list-calendars.rs"]
pub mod list_calendars;
#[path = "list-items.rs"]
pub mod list_items;
#[path = "read-item.rs"]
pub mod read_item;
#[path = "update-calendar.rs"]
pub mod update_calendar;
#[path = "update-item.rs"]
pub mod update_item;
