#[path = "calendar-home-set.rs"]
pub mod calendar_home_set;
#[path = "create-calendar.rs"]
pub mod create_calendar;
#[path = "create-item.rs"]
pub mod create_item;
#[path = "current-user-principal.rs"]
pub mod current_user_principal;
#[path = "delete-calendar.rs"]
pub mod delete_calendar;
#[path = "delete-item.rs"]
pub mod delete_item;
#[path = "follow-redirects.rs"]
pub mod follow_redirects;
#[path = "list-calendars.rs"]
pub mod list_calendars;
#[path = "list-items.rs"]
pub mod list_items;
#[path = "read-item.rs"]
pub mod read_item;
pub mod send;
#[path = "update-calendar.rs"]
pub mod update_calendar;
#[path = "update-item.rs"]
pub mod update_item;
#[path = "well-known.rs"]
pub mod well_known;
